Fix CI

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -21,7 +21,9 @@ jobs:
         wget https://packages.chef.io/files/stable/chefdk/4.7.73/ubuntu/18.04/chefdk_4.7.73-1_amd64.deb
         sudo dpkg -i chefdk_4.7.73-1_amd64.deb
         eval "$(chef shell-init bash)"
+    - name: Linting
+      run: cookstyle -D || (echo "Run 'cookstyle -a' to correct cookstyle errors." && exit 1)
     - name: Ubuntu-20
-      kitchen converge ubuntu-20
+      run: kitchen converge ubuntu-20
     - name: Debian
-      kitchen converge debian
+      run: kitchen converge debian
